### ISSUE TITLE
Compatibility with Logstash 7

### ISSUE THREAD

**Issue by tovern** [ip2location/logstash-filter-ip2location#17]
Is this filter compatible with Logstash 7? As of yet I have been unable to get this to work, it just stalls with the following debug output:

`
[2019-11-15T13:07:53,071][WARN ][org.logstash.execution.ShutdownWatcherExt] {"inflight_count"=>0, "stalling_threads_info"=>{"other"=>[{"thread_id"=>31, "name"=>"[main]<beats", "current_call"=>"[...]/vendor/bundle/jruby/2.5.0/gems/logstash-input-beats-6.0.0-java/lib/logstash/inputs/beats.rb:204:in `run'"}], ["LogStash::Filters::IP2Location", {"database"=>"/etc/logstash/IP-COUNTRY-REGION-CITY-LATITUDE-LONGITUDE-ISP-DOMAIN-MOBILE-USAGETYPE.BIN", "use_memory_mapped"=>"false", "source"=>"[myapp][ip]", "id"=>"eea97c912eb1cf85989f366c1ab2caa33d2377f2c2ff8a369223074ab4f0e037"}]=>[{"thread_id"=>23, "name"=>"[main]>worker0", "current_call"=>"[...]/vendor/bundle/jruby/2.5.0/gems/logstash-filter-ip2location-2.1.0/lib/logstash/filters/ip2location.rb:156:in `synchronize'"}, {"thread_id"=>24, "name"=>"[main]>worker1", "current_call"=>"[...]/vendor/bundle/jruby/2.5.0/gems/logstash-filter-ip2location-2.1.0/lib/logstash/filters/ip2location.rb:156:in `synchronize'"}, {"thread_id"=>25, "name"=>"[main]>worker2", "current_call"=>"[...]/vendor/bundle/jruby/2.5.0/gems/logstash-filter-ip2location-2.1.0/lib/logstash/filters/ip2location.rb:150:in `cache_event'"}, {"thread_id"=>26, "name"=>"[main]>worker3", "current_call"=>"[...]/vendor/bundle/jruby/2.5.0/gems/logstash-filter-ip2location-2.1.0/lib/logstash/filters/ip2location.rb:156:in `synchronize'"}]}}
[2019-11-15T13:07:53,074][ERROR][org.logstash.execution.ShutdownWatcherExt] The shutdown process appears to be stalled due to busy or blocked plugins. Check the logs for more information.
[2019-11-15T13:07:56,051][INFO ][org.logstash.beats.BeatsHandler] [local: 0.0.0.0:5044, remote: x.x.x.x:38272] Handling exception: event executor terminated
`

**Comment by ip2location-com** [comment]
Yes, the filter plugin is compatible with Logstash 7.

Can you update the plugin and try again?
