### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by youngmip** [ip2location/logstash-filter-ip2location#19]
Hi, 

I am using the ip2location filter plugin in Kubernetes cluster. Can you please have a look at the following exception?

`[2020-02-07T10:54:36,726][ERROR][logstash.pipeline        ] Exception in pipelineworker, the pipeline stopped processing new events, please check your filter configuration and restart Logstash. {:pipeline_id=>"main", "exception"=>"", "backtrace"=>["java.util.IdentityHashMap.forEach(IdentityHashMap.java:1358)", "org.logstash.Rubyfier.deepMap(Rubyfier.java:71)", "org.logstash.Rubyfier.lambda$initConverters$8(Rubyfier.java:99)", "org.logstash.Rubyfier.deep(Rubyfier.java:53)", "org.logstash.ext.JrubyEventExtLibrary$RubyEvent.ruby_get_field(JrubyEventExtLibrary.java:83)", "usr.share.logstash.vendor.bundle.jruby.$2_dot_5_dot_0.gems.logstash_minus_filter_minus_ip2location_minus_2_dot_1_dot_1.lib.logstash.filters.ip2location.RUBY$method$filter$0(/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-filter-ip2location-2.1.1/lib/logstash/filters/ip2location.rb:50)", "org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:117)", "org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:156)", "org.jruby.ir.targets.InvokeSite.fail(InvokeSite.java:253)", "usr.share.logstash.logstash_minus_core.lib.logstash.filters.base.RUBY$method$do_filter$0(/usr/share/logstash/logstash-core/lib/logstash/filters/base.rb:143)", "org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:117)", "org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:156)", "org.jruby.ir.targets.InvokeSite.fail(InvokeSite.java:253)", "usr.share.logstash.logstash_minus_core.lib.logstash.filters.base.RUBY$block$multi_filter$1(/usr/share/logstash/logstash-core/lib/logstash/filters/base.rb:162)", "org.jruby.runtime.CompiledIRBlockBody.yieldDirect(CompiledIRBlockBody.java:146)", "org.jruby.runtime.BlockBody.yield(BlockBody.java:114)", "org.jruby.runtime.Block.yield(Block.java:165)", "org.jruby.RubyArray.each(RubyArray.java:1792)", "usr.share.logstash.logstash_minus_core.lib.logstash.filters.base.RUBY$method$multi_filter$0(/usr/share/logstash/logstash-core/lib/logstash/filters/base.rb:159)", "org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:117)", "org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:156)", "org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:200)", "org.logstash.config.ir.compiler.FilterDelegatorExt.doMultiFilter(FilterDelegatorExt.java:99)", "org.logstash.config.ir.compiler.AbstractFilterDelegatorExt.multiFilter(AbstractFilterDelegatorExt.java:115)", "org.logstash.config.ir.compiler.AbstractFilterDelegatorExt$INVOKER$i$1$0$multiFilter.call(AbstractFilterDelegatorExt$INVOKER$i$1$0$multiFilter.gen)", "org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)", "org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:317)", "org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:72)", "org.jruby.ir.interpreter.Interpreter.INTERPRET_BLOCK(Interpreter.java:128)", "org.jruby.runtime.MixedModeIRBlockBody.commonYieldPath(MixedModeIRBlockBody.java:151)", "org.jruby.runtime.IRBlockBody.doYield(IRBlockBody.java:187)", "org.jruby.runtime.BlockBody.yield(BlockBody.java:116)", "org.jruby.runtime.Block.yield(Block.java:165)", "org.jruby.RubyArray.each(RubyArray.java:1792)", "org.jruby.RubyArray$INVOKER$i$0$0$each.call(RubyArray$INVOKER$i$0$0$each.gen)", "org.jruby.internal.runtime.methods.JavaMethod$JavaMethodZeroBlock.call(JavaMethod.java:555)", "org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:80)", "org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:89)", "org.jruby.ir.instructions.CallBase.interpret(CallBase.java:537)", "org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:362)", "org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:72)", "org.jruby.ir.interpreter.Interpreter.INTERPRET_BLOCK(Interpreter.java:128)", "org.jruby.runtime.MixedModeIRBlockBody.commonYieldPath(MixedModeIRBlockBody.java:151)", "org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:79)", "org.jruby.runtime.Block.call(Block.java:124)", "org.jruby.RubyProc.call(RubyProc.java:295)", "org.jruby.RubyProc.call(RubyProc.java:274)", "org.jruby.RubyProc.call(RubyProc.java:266)", "org.jruby.RubyProc$INVOKER$i$0$0$call.call(RubyProc$INVOKER$i$0$0$call.gen)", "org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:204)", "org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:200)", "org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)", "org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:317)", "org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:72)", "org.jruby.ir.interpreter.Interpreter.INTERPRET_BLOCK(Interpreter.java:128)", "org.jruby.runtime.MixedModeIRBlockBody.commonYieldPath(MixedModeIRBlockBody.java:151)", "org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:79)", "org.jruby.runtime.Block.call(Block.java:124)", "org.jruby.RubyProc.call(RubyProc.java:295)", "org.jruby.internal.runtime.methods.ProcMethod.call(ProcMethod.java:64)", "org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:204)", "org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:200)", "usr.share.logstash.logstash_minus_core.lib.logstash.pipeline.RUBY$method$filter_batch$0(/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:358)", "org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:117)", "org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:156)", "org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:200)", "org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)", "org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:317)", "org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:72)", "org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:105)", "org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:92)", "org.jruby.ir.targets.InvokeSite.invoke(InvokeSite.java:183)", "usr.share.logstash.logstash_minus_core.lib.logstash.pipeline.RUBY$block$start_workers$2(/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:304)", "org.jruby.runtime.CompiledIRBlockBody.callDirect(CompiledIRBlockBody.java:136)", "org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:77)", "org.jruby.runtime.Block.call(Block.java:124)", "org.jruby.RubyProc.call(RubyProc.java:295)", "org.jruby.RubyProc.call(RubyProc.java:274)", "org.jruby.RubyProc.call(RubyProc.java:270)", "org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:105)", "java.lang.Thread.run(Thread.java:748)"], :thread=>"#<Thread:0x74cecd62 sleep>"}
warning: thread "[main]>worker1" terminated with exception (report_on_exception is true):
`

Logstash (6.8.6)
logstash-filter-ip2location (2.1.1)
`   	ip2location {
    		source => "ipaddress"
    		database => "${IP2LOCATION_DB:/somwehre/ip2location.BIN}"
    	}
 `

**Comment by antedesk** [comment]
I'm facing the same issue with 
- **Logstash v7.6.1**
- **logstash-filter-ip2location v2.1.1**

**[EDIT]** I'm using docker-compose for running a service based on official logstash image

That's my code for the filter

```
        if [ip] and [ip] != "-" and [ip] != "" {
            ip2location {
                source => "ip"
                database => "/usr/share/logstash/ip2location-db/IP-COUNTRY-REGION-CITY-LATITUDE-LONGITUDE-ISP-DOMAIN-MOBILE-USAGETYPE-SAMPLE.BIN"
                use_memory_mapped => true
            }
        }
```
While the error log is as follow

```
[2020-04-01T10:48:11,660][ERROR][org.logstash.execution.WorkerLoop][main] Exception in pipelineworker, the pipeline stopped processing new events, please check your filter configuration and restart Logstash.
java.util.ConcurrentModificationException: null
 at java.util.IdentityHashMap.forEach(IdentityHashMap.java:1358) ~[?:?]
 at org.logstash.Rubyfier.deepMap(Rubyfier.java:71) ~[logstash-core.jar:?]
 at org.logstash.Rubyfier.lambda$initConverters$8(Rubyfier.java:99) ~[logstash-core.jar:?]
 at org.logstash.Rubyfier.deep(Rubyfier.java:53) ~[logstash-core.jar:?]
 at org.logstash.ext.JrubyEventExtLibrary$RubyEvent.ruby_get_field(JrubyEventExtLibrary.java:85) ~[logstash-core.jar:?]
 at usr.share.logstash.vendor.bundle.jruby.$2_dot_5_dot_0.gems.logstash_minus_filter_minus_ip2location_minus_2_dot_1_dot_1.lib.logstash.filters.ip2location.RUBY$method$filter$0(/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-filter-ip2location-2.1.1/lib/logstash/filters/ip2location.rb:50) ~[?:?]
 at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:110) ~[jruby-complete-9.2.9.0.jar:?]
 at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:140) ~[jruby-complete-9.2.9.0.jar:?]
 at org.jruby.ir.targets.InvokeSite.fail(InvokeSite.java:253) ~[jruby-complete-9.2.9.0.jar:?]
 at usr.share.logstash.logstash_minus_core.lib.logstash.filters.base.RUBY$method$do_filter$0(/usr/share/logstash/logstash-core/lib/logstash/filters/base.rb:143) ~[?:?]
 at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:110) ~[jruby-complete-9.2.9.0.jar:?]
 at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:140) ~[jruby-complete-9.2.9.0.jar:?]
 at org.jruby.ir.targets.InvokeSite.fail(InvokeSite.java:253) ~[jruby-complete-9.2.9.0.jar:?]
 at usr.share.logstash.logstash_minus_core.lib.logstash.filters.base.RUBY$block$multi_filter$1(/usr/share/logstash/logstash-core/lib/logstash/filters/base.rb:162) ~[?:?]
 at org.jruby.runtime.CompiledIRBlockBody.yieldDirect(CompiledIRBlockBody.java:146) ~[jruby-complete-9.2.9.0.jar:?]
 at org.jruby.runtime.BlockBody.yield(BlockBody.java:114) ~[jruby-complete-9.2.9.0.jar:?]
 at org.jruby.runtime.Block.yield(Block.java:170) ~[jruby-complete-9.2.9.0.jar:?]
 at org.jruby.RubyArray.each(RubyArray.java:1814) ~[jruby-complete-9.2.9.0.jar:?]
 at usr.share.logstash.logstash_minus_core.lib.logstash.filters.base.RUBY$method$multi_filter$0(/usr/share/logstash/logstash-core/lib/logstash/filters/base.rb:159) ~[?:?]
 at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:110) ~[jruby-complete-9.2.9.0.jar:?]
 at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:140) ~[jruby-complete-9.2.9.0.jar:?]
 at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:200) ~[jruby-complete-9.2.9.0.jar:?]
 at org.logstash.config.ir.compiler.FilterDelegatorExt.doMultiFilter(FilterDelegatorExt.java:99) ~[logstash-core.jar:?]
 at org.logstash.config.ir.compiler.AbstractFilterDelegatorExt.multiFilter(AbstractFilterDelegatorExt.java:115) ~[logstash-core.jar:?]
 at org.logstash.generated.CompiledDataset30.compute(Unknown Source) ~[?:?]
 at org.logstash.generated.CompiledDataset31.compute(Unknown Source) ~[?:?]
 at org.logstash.generated.CompiledDataset32.compute(Unknown Source) ~[?:?]
 at org.logstash.generated.CompiledDataset33.compute(Unknown Source) ~[?:?]
 at org.logstash.generated.CompiledDataset34.compute(Unknown Source) ~[?:?]
 at org.logstash.generated.CompiledDataset35.compute(Unknown Source) ~[?:?]
 at org.logstash.generated.CompiledDataset36.compute(Unknown Source) ~[?:?]
 at org.logstash.generated.CompiledDataset37.compute(Unknown Source) ~[?:?]
 at org.logstash.generated.CompiledDataset38.compute(Unknown Source) ~[?:?]
 at org.logstash.generated.CompiledDataset39.compute(Unknown Source) ~[?:?]
 at org.logstash.generated.CompiledDataset40.compute(Unknown Source) ~[?:?]
 at org.logstash.generated.CompiledDataset42.compute(Unknown Source) ~[?:?]
 at org.logstash.generated.CompiledDataset43.compute(Unknown Source) ~[?:?]
 at org.logstash.generated.CompiledDataset45.compute(Unknown Source) ~[?:?]
 at org.logstash.execution.WorkerLoop.run(WorkerLoop.java:64) [logstash-core.jar:?]
 at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
 at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
 at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
 at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
 at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(JavaMethod.java:441) [jruby-complete-9.2.9.0.jar:?]
 at org.jruby.javasupport.JavaMethod.invokeDirect(JavaMethod.java:305) [jruby-complete-9.2.9.0.jar:?]
 at org.jruby.java.invokers.InstanceMethodInvoker.call(InstanceMethodInvoker.java:32) [jruby-complete-9.2.9.0.jar:?]
 at usr.share.logstash.logstash_minus_core.lib.logstash.java_pipeline.RUBY$block$start_workers$5(/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:262) [jruby-complete-9.2.9.0.jar:?]
 at org.jruby.runtime.CompiledIRBlockBody.callDirect(CompiledIRBlockBody.java:136) [jruby-complete-9.2.9.0.jar:?]
 at org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:77) [jruby-complete-9.2.9.0.jar:?]
 at org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:71) [jruby-complete-9.2.9.0.jar:?]
 at org.jruby.runtime.Block.call(Block.java:125) [jruby-complete-9.2.9.0.jar:?]
 at org.jruby.RubyProc.call(RubyProc.java:274) [jruby-complete-9.2.9.0.jar:?]
 at org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:105) [jruby-complete-9.2.9.0.jar:?]
 at java.lang.Thread.run(Thread.java:834) [?:?]
warning: thread "[main]>worker1" terminated with exception (report_on_exception is true):
java.lang.IllegalStateException: java.util.ConcurrentModificationException
 at org.logstash.execution.WorkerLoop.run(org/logstash/execution/WorkerLoop.java:85)
 at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(jdk/internal/reflect/NativeMethodAccessorImpl.java:62)
 at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(jdk/internal/reflect/DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:566)
 at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(org/jruby/javasupport/JavaMethod.java:441)
 at org.jruby.javasupport.JavaMethod.invokeDirect(org/jruby/javasupport/JavaMethod.java:305)
 at usr.share.logstash.logstash_minus_core.lib.logstash.java_pipeline.start_workers(/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:262)
 at org.jruby.RubyProc.call(org/jruby/RubyProc.java:274)
 at java.lang.Thread.run(java/lang/Thread.java:834)
Caused by: java.util.ConcurrentModificationException
 at java.base/java.util.IdentityHashMap.forEach(IdentityHashMap.java:1358)
 at org.logstash.Rubyfier.deepMap(Rubyfier.java:71)
 at org.logstash.Rubyfier.lambda$initConverters$8(Rubyfier.java:99)
 at org.logstash.Rubyfier.deep(Rubyfier.java:53)
 at org.logstash.ext.JrubyEventExtLibrary$RubyEvent.ruby_get_field(JrubyEventExtLibrary.java:85)
 at usr.share.logstash.vendor.bundle.jruby.$2_dot_5_dot_0.gems.logstash_minus_filter_minus_ip2location_minus_2_dot_1_dot_1.lib.logstash.filters.ip2location.RUBY$method$filter$0(/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-filter-ip2location-2.1.1/lib/logstash/filters/ip2location.rb:50)
 at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:110)
 at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:140)
 at org.jruby.ir.targets.InvokeSite.fail(InvokeSite.java:253)
 at usr.share.logstash.logstash_minus_core.lib.logstash.filters.base.RUBY$method$do_filter$0(/usr/share/logstash/logstash-core/lib/logstash/filters/base.rb:143)
 at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:110)
 at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:140)
 at org.jruby.ir.targets.InvokeSite.fail(InvokeSite.java:253)
 at usr.share.logstash.logstash_minus_core.lib.logstash.filters.base.RUBY$block$multi_filter$1(/usr/share/logstash/logstash-core/lib/logstash/filters/base.rb:162)
 at org.jruby.runtime.CompiledIRBlockBody.yieldDirect(CompiledIRBlockBody.java:146)
 at org.jruby.runtime.BlockBody.yield(BlockBody.java:114)
 at org.jruby.runtime.Block.yield(Block.java:170)
 at org.jruby.RubyArray.each(RubyArray.java:1814)
 at usr.share.logstash.logstash_minus_core.lib.logstash.filters.base.RUBY$method$multi_filter$0(/usr/share/logstash/logstash-core/lib/logstash/filters/base.rb:159)
 at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:110)
 at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:140)
 at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:200)
 at org.logstash.config.ir.compiler.FilterDelegatorExt.doMultiFilter(FilterDelegatorExt.java:99)
 at org.logstash.config.ir.compiler.AbstractFilterDelegatorExt.multiFilter(AbstractFilterDelegatorExt.java:115)
 at org.logstash.generated.CompiledDataset30.compute(Unknown Source)
 at org.logstash.generated.CompiledDataset31.compute(Unknown Source)
 at org.logstash.generated.CompiledDataset32.compute(Unknown Source)
 at org.logstash.generated.CompiledDataset33.compute(Unknown Source)
 at org.logstash.generated.CompiledDataset34.compute(Unknown Source)
 at org.logstash.generated.CompiledDataset35.compute(Unknown Source)
 at org.logstash.generated.CompiledDataset36.compute(Unknown Source)
 at org.logstash.generated.CompiledDataset37.compute(Unknown Source)
 at org.logstash.generated.CompiledDataset38.compute(Unknown Source)
 at org.logstash.generated.CompiledDataset39.compute(Unknown Source)
 at org.logstash.generated.CompiledDataset40.compute(Unknown Source)
 at org.logstash.generated.CompiledDataset42.compute(Unknown Source)
 at org.logstash.generated.CompiledDataset43.compute(Unknown Source)
 at org.logstash.generated.CompiledDataset45.compute(Unknown Source)
 at org.logstash.execution.WorkerLoop.run(WorkerLoop.java:64)
 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.base/java.lang.reflect.Method.invoke(Method.java:566)
 at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(JavaMethod.java:441)
 at org.jruby.javasupport.JavaMethod.invokeDirect(JavaMethod.java:305)
 at org.jruby.java.invokers.InstanceMethodInvoker.call(InstanceMethodInvoker.java:32)
 at usr.share.logstash.logstash_minus_core.lib.logstash.java_pipeline.RUBY$block$start_workers$5(/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:262)
 at org.jruby.runtime.CompiledIRBlockBody.callDirect(CompiledIRBlockBody.java:136)
 at org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:77)
 at org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:71)
 at org.jruby.runtime.Block.call(Block.java:125)
 at org.jruby.RubyProc.call(RubyProc.java:274)
 at org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:105)
 at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by ip2location-com** [comment]
Kindly try it again with the latest version 2.1.2.

**Comment by youngmip** [comment]
> Kindly try it again with the latest version 2.1.2.

Thanks. I will try shortly

**Comment by YTS85205107** [comment]
Hi, 

I'm facing the same issue again

Logstash version : 8.15.2
logstash-filter-ip2location version : 2.5.0

[2024-12-04T04:11:48,694][ERROR][logstash.javapipeline    ][saba-detector] Pipeline worker error, the pipeline will be stopped {:pipeline_id=>"saba-detector", :error=>"", :exception=>Java::JavaUtil::ConcurrentModificationException, :backtrace=>["java.base/java.util.IdentityHashMap.forEach(IdentityHashMap.java:1379)",
"org.logstash.Rubyfier.deepMap(Rubyfier.java:97)",
"org.logstash.Rubyfier.lambda$initConverters$8(Rubyfier.java:125)",
"org.logstash.Rubyfier.deep(Rubyfier.java:79)",
"org.logstash.ext.JrubyEventExtLibrary$RubyEvent.ruby_get_field(JrubyEventExtLibrary.java:107)",
"usr.share.logstash.vendor.bundle.jruby.$3_dot_1_dot_0.gems.logstash_minus_filter_minus_ip2location_minus_2_dot_5_dot_0.lib.logstash.filters.ip2location.RUBY$method$filter$0(/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/logstash-filter-ip2location-2.5.0/lib/logstash/filters/ip2location.rb:76)",
"org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:165)",
"org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:185)",
"org.jruby.ir.targets.indy.InvokeSite.failf(InvokeSite.java:855)",
"usr.share.logstash.logstash_minus_core.lib.logstash.filters.base.RUBY$method$do_filter$0(/usr/share/logstash/logstash-core/lib/logstash/filters/base.rb:158)",
"org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:165)",
"org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:185)",
"org.jruby.ir.targets.indy.InvokeSite.failf(InvokeSite.java:855)",
"usr.share.logstash.logstash_minus_core.lib.logstash.filters.base.RUBY$block$multi_filter$1(/usr/share/logstash/logstash-core/lib/logstash/filters/base.rb:176)",
"org.jruby.runtime.CompiledIRBlockBody.yieldDirect(CompiledIRBlockBody.java:151)",
"org.jruby.runtime.BlockBody.yield(BlockBody.java:106)",
"org.jruby.runtime.Block.yield(Block.java:189)",
"org.jruby.RubyArray.each(RubyArray.java:1981)", "usr.share.logstash.logstash_minus_core.lib.logstash.filters.base.RUBY$method$multi_filter$0(/usr/share/logstash/logstash-core/lib/logstash/filters/base.rb:173)",
"org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:165)",
"org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:185)",
"org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:220)",
"org.logstash.config.ir.compiler.FilterDelegatorExt.doMultiFilter(FilterDelegatorExt.java:128)",
"org.logstash.config.ir.compiler.AbstractFilterDelegatorExt.lambda$multiFilter$0(AbstractFilterDelegatorExt.java:133)",
"org.logstash.instrument.metrics.timer.ConcurrentLiveTimerMetric.time(ConcurrentLiveTimerMetric.java:47)",
"org.logstash.config.ir.compiler.AbstractFilterDelegatorExt.multiFilter(AbstractFilterDelegatorExt.java:133)",
"org.logstash.generated.CompiledDataset4.compute(Unknown Source)",
"org.logstash.generated.CompiledDataset4.compute(Unknown Source)",
"org.logstash.generated.CompiledDataset4.compute(Unknown Source)",
"org.logstash.generated.CompiledDataset4.compute(Unknown Source)",
"org.logstash.generated.CompiledDataset4.compute(Unknown Source)",
"org.logstash.generated.CompiledDataset4.compute(Unknown Source)",
"org.logstash.generated.CompiledDataset4.compute(Unknown Source)",
"org.logstash.generated.CompiledDataset4.compute(Unknown Source)",
"org.logstash.config.ir.CompiledPipeline$CompiledUnorderedExecution.compute(CompiledPipeline.java:347)",
"org.logstash.config.ir.CompiledPipeline$CompiledUnorderedExecution.compute(CompiledPipeline.java:341)",
"org.logstash.execution.ObservedExecution.lambda$compute$0(ObservedExecution.java:17)",
"org.logstash.execution.WorkerObserver.lambda$observeExecutionComputation$0(WorkerObserver.java:39)",
"org.logstash.instrument.metrics.timer.ConcurrentLiveTimerMetric.time(ConcurrentLiveTimerMetric.java:47)",
"org.logstash.execution.WorkerObserver.lambda$executeWithTimers$1(WorkerObserver.java:50)",
"org.logstash.instrument.metrics.timer.ConcurrentLiveTimerMetric.time(ConcurrentLiveTimerMetric.java:47)", 
"org.logstash.execution.WorkerObserver.executeWithTimers(WorkerObserver.java:50)",
"org.logstash.execution.WorkerObserver.observeExecutionComputation(WorkerObserver.java:38)",
"org.logstash.execution.ObservedExecution.compute(ObservedExecution.java:17)",
"org.logstash.execution.WorkerLoop.abortableCompute(WorkerLoop.java:113)",
"org.logstash.execution.WorkerLoop.run(WorkerLoop.java:86)",
"java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)",
"java.base/java.lang.reflect.Method.invoke(Method.java:580)",
"org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(JavaMethod.java:300)",
"org.jruby.javasupport.JavaMethod.invokeDirect(JavaMethod.java:164)",
"org.jruby.java.invokers.InstanceMethodInvoker.call(InstanceMethodInvoker.java:32)",
"org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:193)",
"org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:346)",
"org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:66)",
"org.jruby.ir.interpreter.Interpreter.INTERPRET_BLOCK(Interpreter.java:118)",
"org.jruby.runtime.MixedModeIRBlockBody.commonYieldPath(MixedModeIRBlockBody.java:136)",
"org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:66)",
"org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:58)",
"org.jruby.runtime.Block.call(Block.java:144)",
"org.jruby.RubyProc.call(RubyProc.java:354)",
"org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:111)",
"java.base/java.lang.Thread.run(Thread.java:1583)"], :thread=>"#<Thread:0x4a39bd20 /usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:134 sleep>"}
